Namespace: learn

Environment: int

ReplicaCount: 1

Service:
  name: learn-svc
  port: 3000
  targetPort: 3000
  nodePort: 32002
  image: rohit273/learn-ed-app
  tag: latest

  type: NodePort

Ingress:
  enabled: true
  host: localhost
  nginxIngressController:
    enabled: true
    class: nginx

Host: learn.app

