apiVersion: v1
kind: Service
metadata:
  name: learn-svc
  namespace: {{ .Values.Namespace }}
spec:
  type: {{ .Values.Service.type }}
  selector:
    app.kubernetes.io/name: learn-svc
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.Service.port }}
      targetPort: {{ .Values.Service.targetPort }}
      nodePort: {{ .Values.Service.nodePort }}